"""Constants for public portfolio approval detection."""

from pathlib import Path

DEFAULT_PUBLIC_PORTFOLIO_CONFIG = "public_portfolios.json"
DEFAULT_PUBLIC_PORTFOLIO_DEFAULTS = str(Path(__file__).resolve().parents[2] / "public_portfolios.defaults.json")

PUBLIC_PORTFOLIO_PAGE_TIMEOUT_MS = 120000
PUBLIC_PORTFOLIO_INITIAL_WAIT_MS = 10000
PUBLIC_PORTFOLIO_SCROLL_WAIT_MS = 5000
PUBLIC_PORTFOLIO_MAX_SCROLLS = 250
PUBLIC_PORTFOLIO_STABLE_SCROLLS = 3
PUBLIC_PORTFOLIO_MAX_PAGES = 2000
PUBLIC_PORTFOLIO_MAX_STALE_PAGES = 3
